name: Run Make Test

on:
  push:
    branches:
      - '**'  # Run on all branches
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up build environment
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Run make test
        run: make test
